# task and env
env:
  env_name: CartPole-v1

# collector
collector:
  frames_per_batch: 128
  total_frames: 1_000_000

# logger
logger:
  backend: wandb
  project_name: ppo_recurrent
  group_name: null
  exp_name: baseline
  test_interval: 1_000_000
  num_test_episodes: 5
  video: False
  mode: online

# Optim
optim:
  lr: 3e-4
  weight_decay: 0.0
  anneal_lr: False
  device:

# loss
loss:
  gamma: 0.99
  mini_batch_size: 32
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coef: 0.5
  entropy_coef: 0.01
  loss_critic_type: l2

compile:
  compile: False
  compile_mode:
  cudagraphs: False