# Environment
env:
  env_name: Sokoban-small-v0
  num_envs: 1
  
# collector
collector:
  frames_per_batch: 4096
  total_frames: 10_000_000

# logger
logger:
  backend: wandb
  project_name: ppo_sokoban
  group_name: null
  exp_name: baseline
  test_interval: 100_000
  num_test_episodes: 3
  video: False
  mode: online

# Optim
optim:
  lr: 2.5e-4
  eps: 1.0e-6
  weight_decay: 0.0
  max_grad_norm: 0.5
  anneal_lr: True
  device: 

# loss
loss:
  gamma: 1.0
  mini_batch_size: 32 #we need to chunk these..
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.1
  anneal_clip_epsilon: True
  critic_coef: 1.0
  entropy_coef: 0.01
  loss_critic_type: l2

compile:
  compile: False
  compile_mode:
  cudagraphs: False