# task and env
env:
  env_name: HalfCheetah-v4
  episode_max_len: 1000

rb:
  num_trajectories: 1000
  trajectory_length: 1000
  slice_len: 2
  batch_size: 2000 #slice len = 2, so 32 slices
  saved_rb_name: random_buffer_halfcheetah_v4

optim:
  pretrain_gradient_steps: 10_000

# logger
logger:
  backend: wandb
  project_name: state_prediction_task
  group_name: null
  exp_name: Predict_Head_Place
  test_interval: 10_000
  num_test_episodes: 5
  mode: online

cell_placement:
  seed: 42
  num_head_cells: 24
  num_place_cells: 384

model:
  num_cells: 512