# task and env
env:
  #env_name: HalfCheetah-v4
  env_name: Swimmer-v5
  episode_max_len: 1000

rb:
  num_trajectories: 1000
  trajectory_length: 1000
  slice_len: 1
  batch_size: 2000
  saved_dir: random_buffer_swimmer_v5
  saved_base_path: data
  num_cat_frames: 2

optim:
  pretrain_gradient_steps: 10_000

# logger
logger:
  backend: wandb
  project_name: energy_predictor
  group_name: current_state_none_energy_place_n_head_dropout_swimmer_v5
  exp_name: predictor
  test_interval: 1_000
  num_test_episodes: 5
  mode: online

artefacts:
  model_save_base_path: models
  model_save_dir: current_state_none_energy_place_n_head_dropout_swimmer_v5

energy_prediction:
  seed: 100

#inputs
  from_source: "current_state" #previous_state, current_state
  delta: "none" #action, path, delta, none
  use_dropout: True
#outputs
  num_place_cells: 256
  num_head_cells: 256
  num_energy_heads: 256
  num_cells: 256
  predict_state_mse: False

