# task and env
env:
  env_name: HalfCheetah-v4

# collector
collector:
  frames_per_batch: 1000 # N x 1000 for full episodes
  total_frames: 10_000_000
  env_per_collector: 20

# logger
logger:
  backend: wandb
  project_name: torchrl_example_ppo
  group_name: null
  exp_name: Mujoco_Schulman17
  test_interval: 1_000_000
  num_test_episodes: 5
  video: False
  mode: online

# Optim
optim:
  lr: 3e-4
  weight_decay: 0.0
  anneal_lr: True
  device:

# loss
loss:
  gamma: 0.99
  mini_batch_size: 1000
  ppo_epochs: 2
  gae_lambda: 0.95
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coef: 1.0
  entropy_coef: 0.0
  loss_critic_type: l2
  bootstrap_rs_value_target: "parallel" #single, episodes

compile:
  compile: False
  compile_mode:
  cudagraphs: False