# task and env
env:
#  env_name: HalfCheetah-v4
  env_name: Swimmer-v5

# collector
collector:
  frames_per_batch: 2048
  total_frames: 10_000

# logger
logger:
  backend: wandb
  project_name: Grid_Comparison
  group_name: null
  exp_name: PPO_Grid_Swimmer
  test_interval: 10_000
  num_test_episodes: 5
  mode: disabled


# Optim
optim:
  lr: 3e-4
  weight_decay: 0.0
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  mini_batch_size: 64
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coef: 0.25
  entropy_coef: 0.0
  loss_critic_type: l2

energy_prediction:
  model_save_base_path: models
  model_save_dir: model_state_swimmer_v5